import "dotenv/config";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { atomicWriteJson } from "../../src/util.js";
import {
  loadVisibilityGroundTruth,
  resolveVisibilityDataset,
  visibilityResultsDir,
} from "./ground-truth.js";
import { buildVisibilityScores } from "./grade.js";
import { loadVisibilityRecords } from "./records.js";
import type { GradedCell, VisibilityModelMetrics, VisibilityScores } from "./types.js";

function pct(value: number | null): string {
  return value === null ? "–" : `${(100 * value).toFixed(0)}%`;
}

function num(value: number | null, digits: number, suffix = ""): string {
  return value === null ? "–" : `${value.toFixed(digits)}${suffix}`;
}

function money(value: number | null): string {
  return value === null ? "–" : `$${value.toFixed(4)}`;
}

/** Escape a cell so an element description containing a pipe cannot break the table. */
function cell(text: string): string {
  return text.replaceAll("|", "\\|").replaceAll(/\r?\n/g, " ");
}

function complement(value: number | null): number | null {
  return value === null ? null : 1 - value;
}

function leaderboardRow(m: VisibilityModelMetrics): string {
  return `| ${m.series} | ${m.provider} | ${m.reasoningEffort} | ${pct(m.accuracy)} | ${pct(m.presentRecall)} | ${pct(m.absentAccuracy)} | ${pct(complement(m.absentAccuracy))} | ${pct(m.visiblePromptAccuracy)} | ${pct(m.hiddenPromptAccuracy)} | ${pct(m.allCorrectRate)} | ${pct(m.flakiness)} | ${num(m.latencyMedianSeconds, 1, "s")} / ${num(m.latencyP95Seconds, 1, "s")} | ${money(m.meanCostPerRun)} | ${money(m.totalCost)} | ${num(m.meanReasoningTokens, 0)} | ${m.textMismatches || ""} | ${m.failedRuns || ""} | ${m.invalidRuns || ""} |`;
}

function matrixCell(cells: readonly GradedCell[]): string {
  const ok = cells.filter((c) => c.status === "ok");
  if (ok.length === 0) return "–";
  const shrunk = ok.length < cells.length ? "†" : "";
  const allCorrect = ok.filter((c) => c.allCorrect === true).length;
  const answers = ok.flatMap((c) => c.elements);
  const accuracy = answers.filter((e) => e.correct).length / answers.length;
  return `${allCorrect}/${ok.length} · ${pct(accuracy)}${shrunk}`;
}

/**
 * Flag any call whose elements all expect the same answer. Such a call can be
 * passed by answering uniformly without looking at the image, so it measures
 * almost nothing — mixing `| TRUE` / `| FALSE` flags into that section fixes it.
 */
export function uniformityWarnings(scores: VisibilityScores): string[] {
  const lines: string[] = [];
  for (const image of scores.images) {
    for (const [mode, elements] of [
      ["is it visible?", image.visibleCall],
      ["is it hidden?", image.hiddenCall],
    ] as const) {
      if (elements.length < 2) continue;
      const expectations = new Set(elements.map((e) => image.expectedVisible.includes(e)));
      if (expectations.size > 1) continue;
      lines.push(
        `> **Uniform answers:** every element asked \`${mode}\` for \`${image.filename}\` expects the` +
          ` same answer, so a model can pass that call without reading the image. Add a` +
          ` \`| FALSE\` bullet to that section to mix it.`,
        "",
      );
    }
  }
  return lines;
}

/**
 * Markdown report: a per-image matrix, a per-element breakdown (where
 * hallucinations become legible), and the leaderboard.
 */
export function buildVisibilityResultsMarkdown(scores: VisibilityScores): string {
  const series = scores.models.map((m) => m.series);
  const elementCount = scores.images.reduce((sum, i) => sum + i.elements.length, 0);
  const reps = new Set(scores.cells.map((c) => c.rep)).size;

  const lines: string[] = [
    "# Element visibility benchmark results",
    "",
    "Generated by `pnpm visibility:report`. Do not edit by hand — re-run the pipeline instead.",
    "",
    `**Dataset:** \`${scores.dataset}\` — ${scores.images.length} image(s), ${elementCount} element(s) under test.`,
    "",
    'Elements under `### visible` are asked with the `elementsVisible()` prompt ("X is fully',
    'visible"); those under `### absent` with the `elementsHidden()` prompt ("X is NOT visible").',
    'Each rep makes one call per prompt. Answers are normalised to "is it on screen?" before',
    "grading, so every rate below means the same thing in both modes. Grading is deterministic:",
    "the model's boolean is compared with the ground truth. There is no judge.",
    "",
  ];

  if (scores.staleRecords > 0) {
    lines.push(
      `> **${scores.staleRecords} stale record(s) ignored.** They were produced from different image bytes or a different element wording than the ground truth now holds. Re-run \`pnpm visibility:run\` to refresh them.`,
      "",
    );
  }

  lines.push("## Image × model matrix", "");
  if (series.length === 0) {
    lines.push("_No graded runs._", "");
  } else {
    lines.push(
      `| Image | Elements | ${series.join(" | ")} |`,
      `| --- | --- | ${series.map(() => "---").join(" | ")} |`,
      ...scores.images.map((image) => {
        const cols = series.map((s) =>
          matrixCell(scores.cells.filter((c) => c.series === s && c.filename === image.filename)),
        );
        const absentCount = image.elements.length - image.expectedVisible.length;
        return `| ${cell(image.filename)} | ${image.expectedVisible.length} visible / ${absentCount} absent | ${cols.join(" | ")} |`;
      }),
      "",
      "Cell: reps where **every** element was correct / successful reps · mean element accuracy.",
      "`†` marks a cell whose denominator shrank because a rep failed or returned an unusable response.",
      "",
    );
  }

  lines.push("## Per-element breakdown", "");
  if (series.length === 0) {
    lines.push("_No graded runs._", "");
  } else {
    for (const image of scores.images) {
      lines.push(
        `### ${image.filename}`,
        "",
        `| Element | Asked as | Expected | ${series.join(" | ")} |`,
        `| --- | --- | --- | ${series.map(() => "---").join(" | ")} |`,
        ...image.elements.map((element) => {
          const askedAs = image.visibleCall.includes(element) ? "is it visible?" : "is it hidden?";
          const expected = image.expectedVisible.includes(element) ? "visible" : "absent";
          const cols = series.map((s) => {
            const answers = scores.cells
              .filter((c) => c.series === s && c.filename === image.filename && c.status === "ok")
              .flatMap((c) => c.elements.filter((e) => e.element === element));
            if (answers.length === 0) return "–";
            return `${answers.filter((a) => a.correct).length}/${answers.length}`;
          });
          return `| ${cell(element)} | ${askedAs} | ${expected} | ${cols.join(" | ")} |`;
        }),
        "",
      );
    }
    lines.push(
      "Cell: reps that answered this element correctly / successful reps.",
      "",
      "**Asked as** is the prompt the element was sent under, and **Expected** the true answer.",
      'A row where the two disagree — asked "is it visible?" but expected absent — comes from a',
      "bullet written with `| FALSE`, and is the sharpest test in the set: the model has to read",
      "the description rather than pattern match on a word it recognises.",
      "",
      ...uniformityWarnings(scores),
    );
  }

  lines.push(
    "## Leaderboard",
    "",
    "Column definitions:",
    "",
    "- **Accuracy** — correct answers over every element of every successful run. The primary ranking column.",
    "- **Present recall** — share of elements that *are* on screen the model confirmed. Misses here mean the model overlooked something real.",
    "- **Absent acc.** — share of elements that are *not* on screen the model correctly denied.",
    "- **Halluc.** — 1 − absent accuracy: how often the model claimed to see something that is not there. This is the failure mode a visibility assertion exists to catch, so read it before accuracy.",
    "- **Visible prompt / Hidden prompt** — accuracy split by which template asked. A wide gap means the model is sensitive to the phrasing rather than to the image, which is worth knowing before you pick `elementsVisible` or `elementsHidden` in a test suite.",
    "- **All-correct** — share of successful runs in which every element of an image was right. A stricter bar than accuracy: one wrong element fails the run.",
    "- **Flakiness** — share of (image, element) pairs answered inconsistently across reps.",
    "- **Text mism.** — graded answers whose returned statement did not echo the element text. Grading is by index regardless; a large count means the model reworded or reordered statements and is worth inspecting.",
    "- **Invalid** — successful calls whose response could not be matched to the elements sent (wrong statement count). Excluded from every rate above rather than counted as wrong.",
    "",
    "| Model | Provider | Effort | Accuracy | Present recall | Absent acc. | Halluc. | Visible prompt | Hidden prompt | All-correct | Flakiness | Latency med/p95 | Cost/run | Total cost | Reasoning tok | Text mism. | Failed | Invalid |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...scores.models.map(leaderboardRow),
    "",
    `- **Generated:** ${scores.generatedAt}`,
    `- **Repeats observed:** ${reps} per model × image`,
    "",
  );
  return lines.join("\n");
}

export function scoresPath(resultsDir: string): string {
  return join(resultsDir, "scores.json");
}

export function resultsMdPath(resultsDir: string): string {
  return join(resultsDir, "RESULTS.md");
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: { dataset: { type: "string" }, models: { type: "string" } },
  });
  const dataset = resolveVisibilityDataset(values.dataset);
  console.log(`Dataset: ${dataset.id} (${dataset.dir})`);

  const images = await loadVisibilityGroundTruth(dataset.dir);
  let records = await loadVisibilityRecords(dataset);

  const modelFilter = values.models
    ?.split(",")
    .map((m) => m.trim())
    .filter(Boolean);
  if (modelFilter) {
    records = records.filter((r) => modelFilter.includes(r.model));
  }

  const scores = buildVisibilityScores(records, images, dataset.id);
  if (scores.cells.length === 0) {
    throw new Error(
      `No gradable run records found under ${visibilityResultsDir(dataset)}. ` +
        `Run "pnpm visibility:run" first.` +
        (scores.staleRecords > 0
          ? ` (${scores.staleRecords} record(s) on disk are stale: the dataset changed since they were produced.)`
          : ""),
    );
  }

  const resultsDir = visibilityResultsDir(dataset);
  await atomicWriteJson(scoresPath(resultsDir), scores);
  await writeFile(resultsMdPath(resultsDir), buildVisibilityResultsMarkdown(scores), "utf8");
  console.log(`Wrote ${scoresPath(resultsDir)}`);
  console.log(`Wrote ${resultsMdPath(resultsDir)}`);
  if (scores.staleRecords > 0) {
    console.log(
      `${scores.staleRecords} stale record(s) ignored — re-run "pnpm visibility:run" to refresh them.`,
    );
  }
}

const isDirectRun = process.argv[1]?.endsWith("report.ts") ?? false;
if (isDirectRun) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
