import "dotenv/config";
import { readdir, writeFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import { parseArgs } from "node:util";
import { benchConfig } from "../../bench.config.js";
import { buildComparisonMarkdown, buildJudgeComparison } from "./compare.js";
import { UNCERTAIN_CONFIDENCE, summarizeConfidence } from "./confidence.js";
import { selectDataset, type Dataset } from "../../shared/dataset.js";
import { buildReportHtml } from "./html.js";
import { ensureManifest } from "./manifest.js";
import { buildMatrix, buildMatrixMarkdown, truncateDescription } from "./matrix.js";
import { overridesPath } from "./score.js";
import {
  OverridesSchema,
  ScoresSchema,
  type Manifest,
  type ModelMetrics,
  type Overrides,
  type Scores,
} from "./types.js";
import { discoveryResultsDir, modelDirName, readJsonIfExists } from "../../shared/util.js";

export function comparisonMdPath(): string {
  return join(discoveryResultsDir(), "JUDGE_COMPARISON.md");
}

/**
 * Per-judge scores files (`scores.<judge-slug>.json`). The slug may contain
 * dots; the unversioned legacy `scores.json` does not match.
 */
export const SCORES_FILE_RE = /^scores\.(.+)\.json$/;

export function resultsMdPathForJudge(judgeModel: string): string {
  return join(discoveryResultsDir(), `RESULTS.${modelDirName(judgeModel)}.md`);
}

export function reportHtmlPathForJudge(judgeModel: string): string {
  return join(discoveryResultsDir(), `report.${modelDirName(judgeModel)}.html`);
}

/** Load every per-judge scores file in the discovery results, sorted by filename. */
export async function discoverScores(): Promise<Scores[]> {
  let files: string[];
  try {
    files = await readdir(discoveryResultsDir());
  } catch {
    return [];
  }
  const scoresList: Scores[] = [];
  for (const file of files.sort()) {
    const match = SCORES_FILE_RE.exec(file);
    if (!match) continue;
    const raw = await readJsonIfExists(join(discoveryResultsDir(), file));
    scoresList.push(ScoresSchema.parse(raw));
  }
  return scoresList;
}

function pct(value: number | null): string {
  return value === null ? "–" : `${(100 * value).toFixed(0)}%`;
}

function num(value: number | null, digits: number, suffix = ""): string {
  return value === null ? "–" : `${value.toFixed(digits)}${suffix}`;
}

function money(value: number | null): string {
  return value === null ? "–" : `$${value.toFixed(4)}`;
}

function leaderboardRow(m: ModelMetrics): string {
  return `| ${m.series} | ${m.provider} | ${m.reasoningEffort} | ${pct(m.meanRecall)} | ${pct(m.anyRecall)} | ${pct(m.flakiness)} | ${num(m.extrasPerRun, 1)} | ${num(m.latencyMedianSeconds, 1, "s")} / ${num(m.latencyP95Seconds, 1, "s")} | ${money(m.meanCostPerRun)} | ${money(m.totalCost)} | ${num(m.meanReasoningTokens, 0)} | ${pct(m.cacheHitRate)} | ${m.failedRuns || ""} |`;
}

/** Section for decision judges (Jev), which attach a probability and confidence to every decision. */
function confidenceMarkdown(scores: Scores): string[] {
  const summary = summarizeConfidence(scores, 15);
  if (!summary) return [];
  const cell = (text: string): string => text.replaceAll("|", "\\|");
  return [
    "## Judge confidence",
    "",
    `\`${scores.judgeModel}\` classified each reported issue as matching an expected defect or as an extra, with a calibrated confidence. ` +
      `${summary.uncertainRuns} of ${summary.judgedRuns} judged run(s) have a decision below confidence ${UNCERTAIN_CONFIDENCE.toFixed(2)}; ` +
      "those are the verdicts worth checking by hand.",
    "",
    "| Confidence | Decisions |",
    "| --- | --- |",
    ...summary.buckets.map((b) => `| ${b.label} | ${b.count} |`),
    "",
    "Least confident decisions:",
    "",
    "| Model | Image | Rep | Issue | Decision | p | Confidence | Reported issue |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ...summary.leastConfident.map(
      (d) =>
        `| ${d.series} | ${d.imageId} | ${d.rep} | R${d.reportedIndex} | ${d.label} | ${d.probability.toFixed(2)} | ${d.confidence.toFixed(2)} | ${cell(truncateDescription(d.description))} |`,
    ),
    "",
  ];
}

export function buildResultsMarkdown(scores: Scores, manifest: Manifest): string {
  const slug = modelDirName(scores.judgeModel);
  const lines = [
    "# Defect discovery benchmark results",
    "",
    "Generated by `pnpm discovery:report`. Do not edit by hand — re-run the pipeline instead.",
    "",
    "## Prompt",
    "",
    "```text",
    scores.prompt,
    "```",
    "",
    `**Judge:** \`${scores.judgeModel}\` (text-only, prompt ${scores.judgePromptVersion}), ${scores.overrideCount} manually overridden cell(s)`,
    "",
    "## Screenshot × model matrix",
    "",
    buildMatrixMarkdown(buildMatrix(scores, manifest)),
    "",
    "## Leaderboard",
    "",
    "Column definitions:",
    "",
    "- **Recall** — mean per-expected-issue detection rate across reps: of a model's successful runs on an image, the share where the judge matched the expected issue, averaged over all expected issues.",
    "- **Recall (any rep)** — share of expected issues the model found in *at least one* rep. The gap to Recall shows how much repetition helps.",
    "- **Flakiness** — share of expected issues the model detects *inconsistently*: found in some reps but not others of the same screenshot (per-issue detection rate strictly between 0% and 100%). High flakiness means the same screenshot gets different answers run to run.",
    "- **Extras/run** — mean number of reported issues per successful run that the judge could not match to any expected issue: false positives / noise. Lower is better.",
    "- **Reasoning tok** — mean reasoning/thinking tokens per run: the actual compute behind the **Effort** label. Effort levels are *not* comparable across vendors — each provider maps them differently — so a row tagged `(low)` can spend more here than another model at `medium`. Read this column, not the tag, when comparing how hard two models thought. Anthropic exposes no separate thinking-token count, so its models show `–` even though they do think.",
    "- **Cache hit** — share of input tokens served from the provider's prompt cache, token-weighted. `–` means the provider reported no cache data at all; `0%` means it reported a cache that never hit. Cost/run applies no cache discount, so a high hit rate means real spend is below the figure shown.",
    "",
    "No composite score: with a small issue set, rank by the columns that matter to you",
    "(default sort: recall desc, extras asc).",
    "",
    "| Model | Provider | Effort | Recall | Recall (any rep) | Flakiness | Extras/run | Latency med/p95 | Cost/run | Total cost | Reasoning tok | Cache hit | Failed |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...scores.models.map(leaderboardRow),
    "",
    ...confidenceMarkdown(scores),
    `- **Generated:** ${scores.generatedAt}`,
    `- **Prompt sha256:** \`${scores.promptHash}\``,
    `- **Reasoning effort:** \`${scores.reasoningEffort}\` (fixed for all models; per-provider mapping documented in the library)`,
    `- **Repeats:** ${scores.repeats} per model × image`,
    "",
    `See \`report.${slug}.html\` (open from the repo) for per-image drill-down and judge-verdict overrides.`,
    "",
  ];
  return lines.join("\n");
}

/**
 * Path from the report file to the dataset directory, for screenshot hrefs.
 * Computed rather than hardcoded so a dataset living outside `bench/datasets/`
 * still resolves when the report is opened from disk.
 */
function imageBaseForReport(dataset: Dataset): string {
  return relative(join(dataset.resultsDir, "discovery"), dataset.dir).split(sep).join("/");
}

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: { judge: { type: "string" }, dataset: { type: "string" } },
  });
  const dataset = selectDataset(values.dataset);
  console.log(`Dataset: ${dataset.id} (${dataset.dir})`);

  const manifest = await ensureManifest();
  let scoresList = await discoverScores();
  if (values.judge) {
    scoresList = scoresList.filter((s) => s.judgeModel === values.judge);
  }
  if (scoresList.length === 0) {
    throw new Error(
      `No scores.<judge>.json files found in ${discoveryResultsDir()}` +
        `${values.judge ? ` for judge "${values.judge}"` : ""}. Run "pnpm discovery:score" first.`,
    );
  }

  const overridesRaw = await readJsonIfExists(overridesPath());
  const overrides: Overrides =
    overridesRaw === undefined ? {} : OverridesSchema.parse(overridesRaw);

  const judges = scoresList.map((s) => s.judgeModel);
  for (const scores of scoresList) {
    const judge = scores.judgeModel;
    const html = buildReportHtml(scores, manifest, overrides, {
      siblingJudges: judges.filter((j) => j !== judge),
      imageBase: imageBaseForReport(dataset),
    });
    const markdown = buildResultsMarkdown(scores, manifest);
    await writeFile(reportHtmlPathForJudge(judge), html, "utf8");
    await writeFile(resultsMdPathForJudge(judge), markdown, "utf8");
    console.log(`Wrote ${reportHtmlPathForJudge(judge)} and ${resultsMdPathForJudge(judge)}`);

    // Canonical copies for the configured default judge keep old links working.
    if (judge === benchConfig.judgeModel) {
      await writeFile(join(discoveryResultsDir(), "report.html"), html, "utf8");
      await writeFile(join(discoveryResultsDir(), "RESULTS.md"), markdown, "utf8");
      console.log(`Wrote canonical RESULTS.md / report.html (default judge)`);
    }
  }

  if (scoresList.length >= 2) {
    const comparison = buildJudgeComparison(scoresList, manifest);
    await writeFile(comparisonMdPath(), buildComparisonMarkdown(comparison), "utf8");
    console.log(`Wrote ${comparisonMdPath()} (${comparison.disagreements.length} disagreement(s))`);
  }
}

const isDirectRun = process.argv[1]?.endsWith("report.ts") ?? false;
if (isDirectRun) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
