import { readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { benchConfig } from "../bench.config.js";
import { buildComparisonMarkdown, buildJudgeComparison } from "./compare.js";
import { buildReportHtml } from "./html.js";
import { ensureManifest } from "./manifest.js";
import { buildMatrix, buildMatrixMarkdown } from "./matrix.js";
import { OVERRIDES_PATH } from "./score.js";
import {
  OverridesSchema,
  ScoresSchema,
  type Manifest,
  type ModelMetrics,
  type Overrides,
  type Scores,
} from "./types.js";
import { RESULTS_DIR, modelDirName, readJsonIfExists } from "./util.js";

export const COMPARISON_MD_PATH = join(RESULTS_DIR, "JUDGE_COMPARISON.md");

/** Per-judge scores files (`scores.<judge-slug>.json`); rejects the legacy `scores.json`. */
export const SCORES_FILE_RE = /^scores\.(.+)\.json$/;

export function resultsMdPathForJudge(judgeModel: string): string {
  return join(RESULTS_DIR, `RESULTS.${modelDirName(judgeModel)}.md`);
}

export function reportHtmlPathForJudge(judgeModel: string): string {
  return join(RESULTS_DIR, `report.${modelDirName(judgeModel)}.html`);
}

/** Load every per-judge scores file in results/, sorted by filename. */
export async function discoverScores(): Promise<Scores[]> {
  let files: string[];
  try {
    files = await readdir(RESULTS_DIR);
  } catch {
    return [];
  }
  const scoresList: Scores[] = [];
  for (const file of files.filter((f) => SCORES_FILE_RE.test(f)).sort()) {
    const raw = await readJsonIfExists(join(RESULTS_DIR, file));
    scoresList.push(ScoresSchema.parse(raw));
  }
  return scoresList;
}

function pct(value: number | null): string {
  return value === null ? "–" : `${(100 * value).toFixed(0)}%`;
}

function num(value: number | null, digits: number, suffix = ""): string {
  return value === null ? "–" : `${value.toFixed(digits)}${suffix}`;
}

function money(value: number | null): string {
  return value === null ? "–" : `$${value.toFixed(4)}`;
}

function leaderboardRow(m: ModelMetrics): string {
  return `| ${m.model} | ${m.provider} | ${pct(m.meanRecall)} | ${pct(m.anyRecall)} | ${pct(m.flakiness)} | ${num(m.extrasPerRun, 1)} | ${num(m.latencyMedianSeconds, 1, "s")} / ${num(m.latencyP95Seconds, 1, "s")} | ${money(m.meanCostPerRun)} | ${money(m.totalCost)} | ${m.failedRuns || ""} |`;
}

export function buildResultsMarkdown(scores: Scores, manifest: Manifest): string {
  const slug = modelDirName(scores.judgeModel);
  const lines = [
    "# Visual reasoning benchmark results",
    "",
    "Generated by `pnpm bench:report`. Do not edit by hand — re-run the pipeline instead.",
    "",
    "## Prompt",
    "",
    "```text",
    scores.prompt,
    "```",
    "",
    `**Judge:** \`${scores.judgeModel}\` (text-only, prompt ${scores.judgePromptVersion}), ${scores.overrideCount} manually overridden cell(s)`,
    "",
    "## Screenshot × model matrix",
    "",
    buildMatrixMarkdown(buildMatrix(scores, manifest)),
    "",
    "## Leaderboard",
    "",
    "Column definitions:",
    "",
    "- **Recall** — mean per-expected-issue detection rate across reps: of a model's successful runs on an image, the share where the judge matched the expected issue, averaged over all expected issues.",
    "- **Recall (any rep)** — share of expected issues the model found in *at least one* rep. The gap to Recall shows how much repetition helps.",
    "- **Flakiness** — share of expected issues the model detects *inconsistently*: found in some reps but not others of the same screenshot (per-issue detection rate strictly between 0% and 100%). High flakiness means the same screenshot gets different answers run to run.",
    "- **Extras/run** — mean number of reported issues per successful run that the judge could not match to any expected issue: false positives / noise. Lower is better.",
    "",
    "No composite score: with a small issue set, rank by the columns that matter to you",
    "(default sort: recall desc, extras asc).",
    "",
    "| Model | Provider | Recall | Recall (any rep) | Flakiness | Extras/run | Latency med/p95 | Cost/run | Total cost | Failed |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...scores.models.map(leaderboardRow),
    "",
    `- **Generated:** ${scores.generatedAt}`,
    `- **Prompt sha256:** \`${scores.promptHash}\``,
    `- **Reasoning effort:** \`${scores.reasoningEffort}\` (fixed for all models; per-provider mapping documented in the library)`,
    `- **Repeats:** ${scores.repeats} per model × image`,
    "",
    `See \`report.${slug}.html\` (open from the repo) for per-image drill-down and judge-verdict overrides.`,
    "",
  ];
  return lines.join("\n");
}

async function main(): Promise<void> {
  const { values } = parseArgs({ options: { judge: { type: "string" } } });

  const manifest = await ensureManifest();
  let scoresList = await discoverScores();
  if (values.judge) {
    scoresList = scoresList.filter((s) => s.judgeModel === values.judge);
  }
  if (scoresList.length === 0) {
    throw new Error(
      `No scores.<judge>.json files found in ${RESULTS_DIR}` +
        `${values.judge ? ` for judge "${values.judge}"` : ""}. Run "pnpm bench:score" first.`,
    );
  }

  const overridesRaw = await readJsonIfExists(OVERRIDES_PATH);
  const overrides: Overrides =
    overridesRaw === undefined ? {} : OverridesSchema.parse(overridesRaw);

  const judges = scoresList.map((s) => s.judgeModel);
  for (const scores of scoresList) {
    const siblingJudges = judges.filter((j) => j !== scores.judgeModel);
    const md = buildResultsMarkdown(scores, manifest);
    const html = buildReportHtml(scores, manifest, overrides, siblingJudges);

    const mdPath = resultsMdPathForJudge(scores.judgeModel);
    const htmlPath = reportHtmlPathForJudge(scores.judgeModel);
    await writeFile(mdPath, md, "utf8");
    await writeFile(htmlPath, html, "utf8");
    console.log(`Wrote ${mdPath}`);
    console.log(`Wrote ${htmlPath}`);

    // Canonical copies for the configured default judge keep old links working.
    if (scores.judgeModel === benchConfig.judgeModel) {
      await writeFile(join(RESULTS_DIR, "RESULTS.md"), md, "utf8");
      await writeFile(join(RESULTS_DIR, "report.html"), html, "utf8");
      console.log(`Wrote canonical RESULTS.md / report.html (default judge)`);
    }
  }

  if (scoresList.length >= 2) {
    const comparison = buildJudgeComparison(scoresList, manifest);
    await writeFile(COMPARISON_MD_PATH, buildComparisonMarkdown(comparison), "utf8");
    console.log(`Wrote ${COMPARISON_MD_PATH} (${comparison.disagreements.length} disagreement(s))`);
  }
}

const isDirectRun = process.argv[1]?.endsWith("report.ts") ?? false;
if (isDirectRun) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
