import { readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { parseArgs } from "node:util";
import {
  DEFAULT_PROMPT_VARIANT,
  PROMPT_VARIANT_IDS,
  benchConfig,
  isPromptVariantId,
} from "../bench.config.js";
import { buildComparisonMarkdown, buildJudgeComparison } from "./compare.js";
import { buildReportHtml, type VariantScores } from "./html.js";
import { ensureManifest } from "./manifest.js";
import { buildMatrix, buildMatrixMarkdown } from "./matrix.js";
import { OVERRIDES_PATH } from "./score.js";
import {
  OverridesSchema,
  ScoresSchema,
  type Manifest,
  type ModelMetrics,
  type Overrides,
  type Scores,
} from "./types.js";
import { RESULTS_DIR, modelDirName, readJsonIfExists } from "./util.js";

export const COMPARISON_MD_PATH = join(RESULTS_DIR, "JUDGE_COMPARISON.md");

/**
 * Per-(variant, judge) scores files (`scores.<variant>.<judge-slug>.json`). The
 * variant is the dot-free first segment; the judge slug follows and may contain
 * dots. Legacy single-segment `scores.<judge>.json` and `scores.json` are
 * rejected here and further filtered by variant id in `discoverScores`.
 */
export const SCORES_FILE_RE = /^scores\.([^.]+)\.(.+)\.json$/;

/** Order variants canonically (baseline first), keeping only those present. */
export function orderVariants(variants: Iterable<string>): string[] {
  const present = new Set(variants);
  return PROMPT_VARIANT_IDS.filter((v) => present.has(v));
}

export function resultsMdPathForVariantJudge(variant: string, judgeModel: string): string {
  return join(RESULTS_DIR, `RESULTS.${variant}.${modelDirName(judgeModel)}.md`);
}

export function reportHtmlPathForJudge(judgeModel: string): string {
  return join(RESULTS_DIR, `report.${modelDirName(judgeModel)}.html`);
}

/**
 * Load every per-(variant, judge) scores file in results/, sorted by filename.
 * Files whose first segment is not a known prompt variant (e.g. leftover legacy
 * `scores.<judge>.json`) are skipped so they never reach schema validation.
 */
export async function discoverScores(): Promise<Scores[]> {
  let files: string[];
  try {
    files = await readdir(RESULTS_DIR);
  } catch {
    return [];
  }
  const scoresList: Scores[] = [];
  for (const file of files.sort()) {
    const match = SCORES_FILE_RE.exec(file);
    if (!match || !isPromptVariantId(match[1] ?? "")) continue;
    const raw = await readJsonIfExists(join(RESULTS_DIR, file));
    scoresList.push(ScoresSchema.parse(raw));
  }
  return scoresList;
}

function pct(value: number | null): string {
  return value === null ? "–" : `${(100 * value).toFixed(0)}%`;
}

function num(value: number | null, digits: number, suffix = ""): string {
  return value === null ? "–" : `${value.toFixed(digits)}${suffix}`;
}

function money(value: number | null): string {
  return value === null ? "–" : `$${value.toFixed(4)}`;
}

function leaderboardRow(m: ModelMetrics): string {
  return `| ${m.series} | ${m.provider} | ${m.reasoningEffort} | ${pct(m.meanRecall)} | ${pct(m.anyRecall)} | ${pct(m.flakiness)} | ${num(m.extrasPerRun, 1)} | ${num(m.latencyMedianSeconds, 1, "s")} / ${num(m.latencyP95Seconds, 1, "s")} | ${money(m.meanCostPerRun)} | ${money(m.totalCost)} | ${m.failedRuns || ""} |`;
}

export function buildResultsMarkdown(scores: Scores, manifest: Manifest): string {
  const slug = modelDirName(scores.judgeModel);
  const lines = [
    "# Visual reasoning benchmark results",
    "",
    "Generated by `pnpm bench:report`. Do not edit by hand — re-run the pipeline instead.",
    "",
    `## Prompt (variant: \`${scores.promptVariant}\`)`,
    "",
    "```text",
    scores.prompt,
    "```",
    "",
    `**Judge:** \`${scores.judgeModel}\` (text-only, prompt ${scores.judgePromptVersion}), ${scores.overrideCount} manually overridden cell(s)`,
    "",
    "## Screenshot × model matrix",
    "",
    buildMatrixMarkdown(buildMatrix(scores, manifest)),
    "",
    "## Leaderboard",
    "",
    "Column definitions:",
    "",
    "- **Recall** — mean per-expected-issue detection rate across reps: of a model's successful runs on an image, the share where the judge matched the expected issue, averaged over all expected issues.",
    "- **Recall (any rep)** — share of expected issues the model found in *at least one* rep. The gap to Recall shows how much repetition helps.",
    "- **Flakiness** — share of expected issues the model detects *inconsistently*: found in some reps but not others of the same screenshot (per-issue detection rate strictly between 0% and 100%). High flakiness means the same screenshot gets different answers run to run.",
    "- **Extras/run** — mean number of reported issues per successful run that the judge could not match to any expected issue: false positives / noise. Lower is better.",
    "",
    "No composite score: with a small issue set, rank by the columns that matter to you",
    "(default sort: recall desc, extras asc).",
    "",
    "| Model | Provider | Effort | Recall | Recall (any rep) | Flakiness | Extras/run | Latency med/p95 | Cost/run | Total cost | Failed |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...scores.models.map(leaderboardRow),
    "",
    `- **Generated:** ${scores.generatedAt}`,
    `- **Prompt sha256:** \`${scores.promptHash}\``,
    `- **Reasoning effort:** \`${scores.reasoningEffort}\` (fixed for all models; per-provider mapping documented in the library)`,
    `- **Repeats:** ${scores.repeats} per model × image`,
    "",
    `See \`report.${slug}.html\` (open from the repo) for per-image drill-down and judge-verdict overrides.`,
    "",
  ];
  return lines.join("\n");
}

async function main(): Promise<void> {
  const { values } = parseArgs({ options: { judge: { type: "string" } } });

  const manifest = await ensureManifest();
  let scoresList = await discoverScores();
  if (values.judge) {
    scoresList = scoresList.filter((s) => s.judgeModel === values.judge);
  }
  if (scoresList.length === 0) {
    throw new Error(
      `No scores.<judge>.json files found in ${RESULTS_DIR}` +
        `${values.judge ? ` for judge "${values.judge}"` : ""}. Run "pnpm bench:score" first.`,
    );
  }

  const overridesRaw = await readJsonIfExists(OVERRIDES_PATH);
  const overrides: Overrides =
    overridesRaw === undefined ? {} : OverridesSchema.parse(overridesRaw);

  // Group scores by judge, then by prompt variant. Each judge gets one HTML
  // report embedding every available variant (switchable in-page) and one
  // markdown file per variant (markdown can't toggle).
  const byJudge = new Map<string, Map<string, Scores>>();
  for (const scores of scoresList) {
    const vmap = byJudge.get(scores.judgeModel) ?? new Map<string, Scores>();
    vmap.set(scores.promptVariant, scores);
    byJudge.set(scores.judgeModel, vmap);
  }
  const judges = [...byJudge.keys()];

  for (const [judge, vmap] of byJudge) {
    const siblingJudges = judges.filter((j) => j !== judge);
    const variantScores: VariantScores[] = orderVariants(vmap.keys()).map((variant) => {
      const scores = vmap.get(variant);
      if (!scores) throw new Error(`Internal: missing scores for variant ${variant}`);
      return { variant, scores };
    });

    const html = buildReportHtml(variantScores, manifest, overrides, siblingJudges);
    const htmlPath = reportHtmlPathForJudge(judge);
    await writeFile(htmlPath, html, "utf8");
    console.log(`Wrote ${htmlPath}`);

    for (const { variant, scores } of variantScores) {
      const mdPath = resultsMdPathForVariantJudge(variant, judge);
      await writeFile(mdPath, buildResultsMarkdown(scores, manifest), "utf8");
      console.log(`Wrote ${mdPath}`);
    }

    // Canonical copies for the configured default judge keep old links working:
    // report.html carries the full variant toggle; RESULTS.md shows the default variant.
    if (judge === benchConfig.judgeModel) {
      const defaultScores = vmap.get(DEFAULT_PROMPT_VARIANT) ?? variantScores[0]?.scores;
      await writeFile(join(RESULTS_DIR, "report.html"), html, "utf8");
      if (defaultScores) {
        await writeFile(
          join(RESULTS_DIR, "RESULTS.md"),
          buildResultsMarkdown(defaultScores, manifest),
          "utf8",
        );
      }
      console.log(`Wrote canonical RESULTS.md / report.html (default judge)`);
    }
  }

  // Judge comparison needs ≥2 judges for the same variant; use the default
  // variant (baseline) when available, else the first variant that qualifies.
  const comparisonVariant = orderVariants(new Set(scoresList.map((s) => s.promptVariant))).find(
    (variant) => scoresList.filter((s) => s.promptVariant === variant).length >= 2,
  );
  if (comparisonVariant) {
    const variantJudges = scoresList.filter((s) => s.promptVariant === comparisonVariant);
    const comparison = buildJudgeComparison(variantJudges, manifest);
    await writeFile(COMPARISON_MD_PATH, buildComparisonMarkdown(comparison), "utf8");
    console.log(
      `Wrote ${COMPARISON_MD_PATH} (variant ${comparisonVariant}, ${comparison.disagreements.length} disagreement(s))`,
    );
  }
}

const isDirectRun = process.argv[1]?.endsWith("report.ts") ?? false;
if (isDirectRun) {
  main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
